<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>Google Drive Example App</title>
    </head>
    <body>
                <h1>Upload File</h1>

    <form method="post" action="<?php echo $url; ?>" enctype="multipart/form-data">
        <input type="file" name="file-up"></input><br>
        <input type="submit" name="submit" value="Upload" style="margin-top: 20px;"></input>
    </form>


 </body>
</html>
